### ISSUE TITLE
Userstory - Signup/Login

### ISSUE THREAD

**Issue by RychardHunt** [RychardHunt/Fyt#42]
---
name: 🚀 Signup/Login
about: As a gym goer, I would want to be able to signup and login with the same credentials.

---

## Feature Request

**Is your feature request related to a problem? Please describe.**
Gym goer should be able to signup for an account and login with the same credentials.

**Describe the solution you'd like**
Firebase Assisted Sign up/Login.

**Describe alternatives you've considered**
Building authentication system from scratch could be a security issue.

**Teachability, Documentation, Adoption, Migration Strategy**
Sign up with email and login with the same email.

**Acceptance Tests**
- [ ] 1. Start the application
- [ ] 2. From the profile screen, press the menu button in the top left of the screen to access the navigation drawer
- [ ] 3. Touch "Register" to navigate to the Register page
- [ ] 4. Enter email in Email TextBox
- [ ] 5. Enter password in Password TextBox
- [ ] 6. Enter the same password in the Confirm Password TextBox
- [ ] 7. Click SIGNUP Button
- [ ] 7. Press the back arrow in the top left of the screen to return to the previous page.
- [ ] 8. Touch the menu button in the top left of the screen
- [ ] 9. Click on Login Button to switch to Login Screen.
- [ ] 10. Enter email in Email TextBox
- [ ] 11. Enter password in Password TextBox
- [ ] 12. Click Login Button
- [ ] 13. Observe the message confirming that you successfully logged in.
