### ISSUE TITLE
Diet Research / Components 

### ISSUE THREAD

**Issue by Stevenn-Li** [RychardHunt/Fyt#46]
Is your feature request related to a problem? Please describe.
As an average person looking to make a change in my physique, I want to be able to receive a diet plan and workout to achieve my goal.

Describe the solution you'd like
Research to be able to come up with a diet plan depending on personal information

Describe alternatives you've considered
-Look at other algorithms to create custom plan

Teachability, Documentation, Adoption, Migration Strategy
-Creates a custom plan for person with images 

Tasks: 
-Images load to show future physique goal
-Meal plan laid out 
-Scroll works
-Layout looks the way I draw it out to be

Acceptance Tests
- [ ] 1. Open the application
- [ ] 2. From the Profile screen, click on the Diet tab at the bottom of the screen
- [ ] 3. Scroll up and down the screen to observe the information available
- [ ] 4. Scroll down to access multiple components of diet / images/ research / information
- [ ] 5. Touch the picture of a bowl of fruit near the bottom of the page to be redirected to the Wegmans website
