### ISSUE TITLE
User Story: Profile

### ISSUE THREAD

**Issue by astewartgit** [RychardHunt/Fyt#50]
As someone interested in fitness I want a profile that shows information about my health

Acceptance test:

Testing the state functionality: 
- [ ] 1. Start the application. You should be on the profile screen.
- [ ] 2. Observe the profile screen, see that the boxes all contain the placeholder values "---"
- [ ] 3. Touch the menu button in the top left of the screen
- [ ] 4. Touch the "Change Profile" button in the menu that came up
- [ ] 5. You are now on the Change Profile Screen.
- [ ] 6. Touch the italicized text that says "Modify Height..." and type a short input (1-6 characters)
- [ ] 7. See the box labelled Height update with your input
- [ ] 8. Touch the italicized text that says "Modify Weight..." and type a short input (1-6 characters)
- [ ] 9. See the box labelled Weight update with your input
- [ ] 10. Touch the italicized text that says "Modify Age..." and type a short input (1-6 characters)
- [ ] 11. See the box labelled Age update with your input
- [ ] 12. Touch the italicized text that says "Modify Streak..." and type a short input (1-6 characters)
- [ ] 13. See the box labelled Streak update with your input
- [ ] 14. Touch the button labelled "Return to Profile..."
- [ ] 15. You are now back on the profile screen. Observe that the boxes have updated to match your inputs.
